blogly/urls.py
# BLOGLY by Alexander Abraham, a.k.a. "Angel Dollface".
# Licensed under the MIT license.

from django.urls import path
from django.urls import include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
]

posts/urls.py
# BLOGLY by Alexander Abraham, a.k.a. "Angel Dollface".
# Licensed under the MIT license.

from .views import post
from .views import post_list
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('', post_list, name='home'),
    path('posts/<int:pk>/', post, name='post'),
]

posts/models.py
# BLOGLY by Alexander Abraham, a.k.a. "Angel Dollface".
# Licensed under the MIT license.

from django.db import models


class Post(models.Model):
    """
    We make a model to store posts.
    """
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=3000)
    body = models.TextField(max_length=50000)
    date = models.DateTimeField(auto_now=True)

posts/views.py
# BLOGLY by Alexander Abraham, a.k.a. "Angel Dollface".
# Licensed under the MIT license.

from .models import Post
from django.shortcuts import render

def post_list(request):
    posts = Post.objects.all()
    context = {'posts':posts}
    return render(request, 'posts/home.html', context)


def post(request, pk):
    post = Post.objects.get(pk=pk)
    title = post.title
    description = post.description
    body = post.body
    date = post.date
    context = {
        'title': title,
        'date': date,
        'description': description,
        'body': body
    }
    return render(request, 'posts/post.html', context)

templates/posts/home.html
<!--
BLOGLY by Alexander Abraham, a.k.a. "Angel Dollface".
Licensed under the MIT license.
-->

{% load static %}
<!DOCTYPE html>
<html>
 <head>
  <title>BLOGLY</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="https://angeldollface.boo/doll-cdn/css/dollfonts.css"/>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
  
 </head>
 <body>

  <img class="pfp" src="{% static 'images/logo.jpg' %}"/>
   
  {% if posts %}
  {% for post in posts %}
  <div class="post">
   <h2 class="title">{{ post.title }}</h2>
   <p class="date">{{ post.date }}</p>
   <hr class="divider"/>
   <p class="description">{{ post.description }}</p>
   <hr class="divider"/>
   <p class="link">
    <a class="link" href="{% url 'posts:post' pk=post.pk %}">READ</a>
   </p>
  </div>
  {% endfor %}
  {% else %}
  <div class="post">
    <h2 class="title">No posts yet!</h2>
    <p class="date">0/0/0 00:00</p>
    <hr class="divider"/>
    <p class="link">No posts have been created yet!</p>
   </div>
  {% endif %}
 </body>
</html>

templates/posts/post.html
<!--
BLOGLY by Alexander Abraham, a.k.a. "Angel Dollface".
Licensed under the MIT license.
-->

{% load static %}
<!DOCTYPE html>
<html>
 <head>
  <title>{{ title }}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="https://angeldollface.boo/doll-cdn/css/dollfonts.css"/>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
 </head>
 <body>
  <img class="pfp" src="{% static 'images/logo.jpg' %}"/>
  <div class="post">
   <h2 class="title">{{ title }}</h2>
   <p class="date">{{ date }}</p>
   <p class="description">{{ description }}</p>
   <hr class="divider"/>
   <p class="body">{{ body }}</p>
  </div>
 </body>
</html>